### ISSUE TITLE
Allow specifying elements for check

### ISSUE THREAD

**Issue by Umarlen** [vue-a11y/vue-axe-next#10]
Hello,

I have a use case where I should check only some specific elements, for example the element with the #header ID, along with all of its content. I would like to be able to customise the selector for the check so vue-axe only analyses my specific components.

Thanks!

**Comment by DiedeGu** [comment]
@Umarlen thank you for your suggestion, we are not going to develop this option. We recommend you use [vitest axe](https://github.com/chaance/vitest-axe) instead, it allows you to run component level tests with axe.
