### ISSUE TITLE
vue-axe not working in Vue 3: Invalid vnode type when creating vnode: undefined

### ISSUE THREAD

**Issue by iknowmagic** [vue-a11y/vue-axe-next#5]
Happy New Year!

Vue is throwing a warning "Invalid vnode type when creating vnode: undefined at <App>" when installing vue-axe@next in Vue 3. I do not see the popup that is supposed to show up on the bottom-right-corner of the screen.

I managed to reproduce the error here: https://codesandbox.io/s/vue-axe-next-error-lz5g2

![image](https://user-images.githubusercontent.com/8712362/148664489-a021b634-d286-4a2f-9921-fb8404ac4801.png)

Many thanks!

**Comment by ktquez** [comment]
Hi, sorry for the delay in responding to your issue.

You can see the usage example in this issue that @olemarius created https://github.com/vue-a11y/vue-axe-next/issues/6
